# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
working_directory: ~/automation_integration_demo
jobs:
  build-and-test-junit-selenium-cucumber:
    docker:
      - image: cimg/openjdk:15.0
    steps:
    - run:
      name: Install Chrome
      command: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get install google-chrome-stable
      # Checkout the code as the first step.
      - checkout
      # Build and run the tests
      - run:
          name: Build and run the Cucumber Selenium tests
          command: |
            cd cucumber-selenium
            mvn clean compile test
      - persist_to_workspace:
          root: ./
          paths:
            - ./cucumber-selenium/target/cucumber-results.xml
  install-trcli-and-parse-results-junit-selenium:
    docker:
      - image: cimg/python:3.11
    steps:
      - attach_workspace:
          at: ./automation_integration_demo
      - run:
          name: Install TR CLI and upload the test results to TestRail
          command: |
            pip install --force-reinstall -v "trcli==1.6.1"
            trcli -y -h $TESTRAIL_INSTANCE_URL --username $TESTRAIL_USERNAME --password $TESTRAIL_PASSWORD parse_junit --title "Automated JUnit Selenium Tests from CircleCI Workflow" --run-description $CIRCLE_BUILD_URL -f "./automation_integration_demo/cucumber-selenium/target/cucumber-results.xml"
# Invoke jobs via workflows
workflows:
  automation-testrail-demo:
    jobs:
      - build-and-test-junit-selenium-cucumber
      - install-trcli-and-parse-results-junit-selenium:
          requires:
            - build-and-test-junit-selenium-cucumber
